# Simple Linear Regression

## Import variables

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

from sklearn.linear_model import LinearRegression

## Load data

In [5]:
data = pd.read_csv('1.01. Simple linear regression.csv')
data.head()

SAT   GPA
0  1714  2.40
1  1664  2.52
2  1760  2.54
3  1685  2.74
4  1693  2.83

## Create Regression

Declare using single feature

In [8]:
x = data['SAT']
y = data['GPA']

In [9]:
y.shape

(84,)

In [14]:
x.shape

(84,)

In [15]:
x_matrix = x.values.reshape(84,1)
y_matrix = y.values.reshape(84,1)

### Regression Itself

In [13]:
reg = LinearRegression()

In [17]:
reg.fit(x_matrix,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

#### R sqaured

In [20]:
reg.score(x_matrix, y)

0.40600391479679765

### Coefficients

In [22]:
reg.coef_

array([0.00165569])

#### Intercept

In [24]:
reg.intercept_

0.275040299660279

## Making Predicts

In [32]:
reg.predict([[1740]])

array([3.15593751])

In [33]:
new_data = pd.DataFrame(data=[1740,1760], columns=['SAT'])

In [35]:
reg.predict(new_data)

array([3.15593751, 3.18905127])

In [41]:
new_data['Predicted_GPA'] = reg.predict(new_data)
new_data

SAT  Predicted_GPA
0  1740       3.155938
1  1760       3.189051