In [1]:
import numpy as np

## Vectors

In [3]:
v = np.array([5, 2, 4])

In [4]:
v

array([5, 2, 4])

## Matrices

In [8]:
m = np.array([[5,12,6],[-3,0,14]])

In [9]:
m

array([[ 5, 12,  6],
       [-3,  0, 14]])

## Data types

In [13]:
type(5)

int

In [14]:
type(m)

numpy.ndarray

In [15]:
s_array = np.array(5)
s_array

array(5)

In [16]:
## Data Shapes

In [17]:
m.shape

(2, 3)

In [18]:
v.shape

(3,)

In [20]:
s_array.shape

()

In [21]:
## tensors

In [22]:
t = np.array([m, m])

In [23]:
t

array([[[ 5, 12,  6],
        [-3,  0, 14]],

       [[ 5, 12,  6],
        [-3,  0, 14]]])

In [25]:
m1 = np.array([[1,2],[2,3]])
m2 = np.array([[-3,4],[0,12]])
m1 - m2

array([[ 4, -2],
       [ 2, -9]])

In [26]:
m1 + 2

array([[3, 4],
       [4, 5]])

## Transposing

In [28]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
a.T ##.T is transpose method

array([[1, 4],
       [2, 5],
       [3, 6]])

In [33]:
vec = np.array([1,2,3])
v = vec.reshape(1,3)

In [34]:
v.T

array([[1],
       [2],
       [3]])