In [3]:
import numpy as np

## Vectors

In [4]:
v = np.array([5, 2, 4])

In [5]:
v

array([5, 2, 4])

## Matrices

In [6]:
m = np.array([[5,12,6],[-3,0,14]])

In [7]:
m

array([[ 5, 12,  6],
       [-3,  0, 14]])

## Data types

In [8]:
type(5)

int

In [9]:
type(m)

numpy.ndarray

In [10]:
s_array = np.array(5)
s_array

array(5)

In [11]:
## Data Shapes

In [12]:
m.shape

(2, 3)

In [13]:
v.shape

(3,)

In [14]:
s_array.shape

()

In [15]:
## tensors

In [16]:
t = np.array([m, m])

In [17]:
t

array([[[ 5, 12,  6],
        [-3,  0, 14]],

       [[ 5, 12,  6],
        [-3,  0, 14]]])

In [18]:
m1 = np.array([[1,2],[2,3]])
m2 = np.array([[-3,4],[0,12]])
m1 - m2

array([[ 4, -2],
       [ 2, -9]])

In [19]:
m1 + 2

array([[3, 4],
       [4, 5]])

## Transposing

In [20]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
a.T ##.T is transpose method

array([[1, 4],
       [2, 5],
       [3, 6]])

In [22]:
vec = np.array([1,2,3])
v = vec.reshape(1,3)

In [23]:
v.T

array([[1],
       [2],
       [3]])

## Dot Product

In [24]:
u = np.array([1,2,3])
v = np.array([3,4,5])
np.dot(u,v)


26

In [25]:
np.dot(5,3)

15

In [26]:
5*u

array([ 5, 10, 15])

In [27]:
np.dot([1,2],[2,3])

8

In [29]:
A = [[1,2,-3],[4,5,6]]
B = [[3,4],[-4,3],[2,4]]
np.dot(A, B)

array([[-11,  -2],
       [  4,  55]])

In [37]:
print(np.array([1.2,-3])*np.array([2,3]))
np.sum(np.array([1.2,-3])*np.array([2,3]))+7

[ 2.4 -9. ]


0.40000000000000036